services:
  - type: web
    name: dispensa-n2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:app" --bind 0.0.0.0:$PORT
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
